In [1]:
import os
import psycopg2
import numpy as np
import pandas as pd
import sqlalchemy as sql

### Считывание переменных окружения + формирование строки подключения

In [2]:
class Settings():
    DB_NAME = os.getenv("DB_NAME")
    DB_HOST = os.getenv("DB_HOST")
    DB_PORT = os.getenv("DB_PORT")
    DB_USER = os.getenv("DB_USER")
    DB_PASSWORD = os.getenv("DB_PASSWORD")

    S3_URL = os.getenv("S3_URL")
    S3_USER = os.getenv("S3_USER")
    S3_PASSWORD = os.getenv("S3_PASSWORD")

    @property
    def DB_URL(self):
        return f"postgresql+psycopg2://{self.DB_USER}:{self.DB_PASSWORD}@{self.DB_HOST}:{self.DB_PORT}/{self.DB_NAME}"

settings = Settings()

### Создание движка и вывод списка доступных для работы таблиц в БД

In [6]:
engine = sql.create_engine(settings.DB_URL)
pd.read_sql("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';", engine)

        table_name
0     oil_stations
1            wells
2       production
3   well_telemetry
4     well_targets
5            pumps
6     pump_sensors
7    pump_failures
8       deliveries
9          drivers
10        vehicles

In [5]:
df = pd.read_sql("SELECT * FROM wells LIMIT 5;", engine)
df

,well_id,name,field_name,region,start_date,operator,status
0,1,Well-101,Severo-Ural,Khanty-Mansi,2018-03-15,UralOil,active
1,2,Well-102,Severo-Ural,Khanty-Mansi,2019-07-22,UralOil,active
2,3,Well-203,Vostok-Field,Yamalo-Nenets,2020-02-11,GazPromTech,maintenance
3,4,Well-304,Zapad-Field,Tomsk,2017-05-01,RosDrill,suspended
4,5,Well-305,Zapad-Field,Tomsk,2019-11-03,RosDrill,active