In [1]:
from common.utils import pipeline

In [2]:
tables = {
    "wells": {
        "date_column": "start_date"
    },
    
    "well_telemetry": {
        "date_column": "timestamp"
    },

    "production": {
        "date_column": "date"
    }
}

results = []

for key in tables.keys():
    results.append(pipeline(table_name=key, date_column=tables[key]["date_column"]))

In [5]:
results[0].isna().any()

well_id       False
name          False
field_name    False
region        False
start_date    False
operator      False
status        False
dtype: bool

In [ ]:
def transforms_outliers(df: pd.DataFrame) -> pd.DataFrame: 
    Q1 = df['column_name'].quantile(0.25) 
    Q3 = df['column_name'].quantile(0.75) 
    IQR = Q3 - Q1 

    lower_bound = Q1 - 1.5 * IQR 
    upper_bound = Q3 + 1.5 * IQR 
    return df[(df['column_name'] >= lower_bound) & (df['column_name'] <= upper_bound)]

In [6]:
results[0]

,well_id,name,field_name,region,start_date,operator,status
0,4,Well-304,Zapad-Field,Tomsk,2017-05-01,RosDrill,suspended
1,1,Well-101,Severo-Ural,Khanty-Mansi,2018-03-15,UralOil,active
2,2,Well-102,Severo-Ural,Khanty-Mansi,2019-07-22,UralOil,active
3,5,Well-305,Zapad-Field,Tomsk,2019-11-03,RosDrill,active
4,3,Well-203,Vostok-Field,Yamalo-Nenets,2020-02-11,GazPromTech,maintenance

In [7]:
results[2]

,prod_id,well_id,date,oil_ton,gas_m3,water_m3,energy_kwh,downtime_hours,temperature,pressure
0,1,1,2025-10-01,212.4,55200.0,182.3,7450.0,0.5,88.1,120.40
1,31,2,2025-10-01,186.1,49800.0,162.0,6800.0,0.8,84.5,115.40
2,61,3,2025-10-01,121.8,40120.0,121.5,5280.0,2.0,79.4,107.10
3,91,4,2025-10-01,0.0,0.0,0.0,0.0,24.0,85.7,117.35
4,121,5,2025-10-01,197.2,52050.0,165.3,7200.0,0.4,86.5,118.80
...,...,...,...,...,...,...,...,...,...,...
145,30,1,2025-10-30,213.0,55240.0,182.1,7460.0,0.4,88.0,120.60
146,60,2,2025-10-30,185.8,49780.0,161.4,6795.0,0.7,84.5,115.30
147,90,3,2025-10-30,121.9,40180.0,121.0,5285.0,2.0,79.4,107.20
148,120,4,2025-10-30,0.0,0.0,0.0,0.0,24.0,85.7,117.35
149,150,5,2025-10-30,199.1,52390.0,165.5,7260.0,0.3,87.0,119.80